### ISSUE TITLE
Apply function pullback broken on RT space on quadrilaterals

### ISSUE THREAD

**Issue by jorgensd** [FEniCS/ufl#311]
MWE:
```python
from ufl import (
    FunctionSpace,
    Mesh,
    Coefficient,
    div,
    dot,
    dx,
    grad,
    triangle,
    quadrilateral, classes
)
from ufl.finiteelement import FiniteElement
from ufl.pullback import contravariant_piola, identity_pullback
from ufl.sobolevspace import H1, HDiv

cell = quadrilateral
RT = FiniteElement("Raviart-Thomas", cell, 1, (2,), contravariant_piola, HDiv)
domain = Mesh(FiniteElement("Lagrange", cell, 1, (2,), identity_pullback, H1))
space = FunctionSpace(domain, RT)

u = Coefficient(space)
J = dot(div(grad(u)), div(grad(u))) * dx

from ufl.algorithms import compute_form_data
compute_form_data(J,
        do_apply_function_pullbacks=True,
        do_apply_integral_scaling=False,
        do_apply_geometry_lowering=False,
        preserve_geometry_types=(classes.Jacobian,),
        do_apply_restrictions=False,
        do_append_everywhere_integrals=False, )
```
Works if one uses `triangle` instead of quadrilateral.
Traceback:
```python
Traceback (most recent call last):
  File "/root/shared/divgrad.py", line 25, in <module>
    compute_form_data(J,
  File "/usr/local/lib/python3.10/dist-packages/ufl/algorithms/compute_form_data.py", line 324, in compute_form_data
    form = apply_derivatives(form)
  File "/usr/local/lib/python3.10/dist-packages/ufl/algorithms/apply_derivatives.py", line 1564, in apply_derivatives
    dexpression_dvar = map_integrand_dags(rules, expression)
  File "/usr/local/lib/python3.10/dist-packages/ufl/algorithms/map_integrands.py", line 86, in map_integrand_dags
    return map_integrands(
  File "/usr/local/lib/python3.10/dist-packages/ufl/algorithms/map_integrands.py", line 29, in map_integrands
    mapped_integrals = [
  File "/usr/local/lib/python3.10/dist-packages/ufl/algorithms/map_integrands.py", line 30, in <listcomp>
    map_integrands(function, itg, only_integral_type) for itg in form.integrals()
  File "/usr/local/lib/python3.10/dist-packages/ufl/algorithms/map_integrands.py", line 39, in map_integrands
    return itg.reconstruct(function(itg.integrand()))
  File "/usr/local/lib/python3.10/dist-packages/ufl/algorithms/map_integrands.py", line 87, in <lambda>
    lambda expr: map_expr_dag(function, expr, compress), form, only_integral_type
  File "/usr/local/lib/python3.10/dist-packages/ufl/corealg/map_dag.py", line 35, in map_expr_dag
    (result,) = map_expr_dags(
  File "/usr/local/lib/python3.10/dist-packages/ufl/corealg/map_dag.py", line 103, in map_expr_dags
    r = handlers[v._ufl_typecode_](v, *[vcache[u] for u in v.ufl_operands])
  File "/usr/local/lib/python3.10/dist-packages/ufl/algorithms/apply_derivatives.py", line 1367, in grad
    return map_expr_dag(rules, f, vcache=self.vcaches[key], rcache=self.rcaches[key])
  File "/usr/local/lib/python3.10/dist-packages/ufl/corealg/map_dag.py", line 35, in map_expr_dag
    (result,) = map_expr_dags(
  File "/usr/local/lib/python3.10/dist-packages/ufl/corealg/map_dag.py", line 101, in map_expr_dags
    r = handlers[v._ufl_typecode_](v)
  File "/usr/local/lib/python3.10/dist-packages/ufl/algorithms/apply_derivatives.py", line 678, in reference_grad
    raise ValueError("ReferenceGrad can only wrap a reference frame type!")
ValueError: ReferenceGrad can only wrap a reference frame type!
```

Originally reported at:
https://fenicsproject.discourse.group/t/a-situation-regarding-the-non-integrability-of-quadrilateral-mesh/15976

**Comment by jorgensd** [comment]
Even simpler form with the same error:
```python
J = u.dx(0).dx(0)[0] * dx
```
