### ISSUE TITLE
uflx and legacy dolfin/ffc support

### ISSUE THREAD

**Issue by drew-parsons** [FEniCS/ufl#99]
ufl 2022.1.0 got released, bringing in modernization of the API. That's great, except some projects will still be using old dolfin.

For instance, the dolfin demos include demo/documented/poisson/cpp/Poisson.ufl, which uses `FiniteElement`. That's been removed from ufl 2022.1.0 (there is `FiniteElementBase` instead), and so running old ffc fails:
```
$ ffc -l dolfin -s -O -r auto Poisson.ufl
Traceback (most recent call last):
  File "/build/dolfin/cmake/scripts/generate-form-files.py", line 90, in <module>
    ret = ffc.main(args)
  File "/usr/lib/python3/dist-packages/ffc/main.py", line 215, in main
    resultcode = _compile_files(args, parameters, enable_profile)
  File "/usr/lib/python3/dist-packages/ffc/main.py", line 248, in _compile_files
    ufd = load_ufl_file(filename)
  File "/usr/lib/python3/dist-packages/ufl/algorithms/formfiles.py", line 181, in load_ufl_file
    namespace = execute_ufl_code(uflcode)
  File "/usr/lib/python3/dist-packages/ufl/algorithms/formfiles.py", line 82, in execute_ufl_code
    exec(uflcode, namespace)
  File "<string>", line 24, in <module>
NameError: name 'FiniteElement' is not defined
```
(this is after patching old ffc with its own copy of [cellname2facetname](https://github.com/FEniCS/ufl/pull/77)).

I think that means it's not feasible to keep patching ffc (and dolfin) to keep up with latest ufl.  Should ufl be renamed as uflx at this point, as was done for the ffc→ffcx transition?

**Comment by drew-parsons** [comment]
In the case of the Poisson.ufl example, it can work by adding
```
from ufl import (Coefficient, dx, ds, inner, grad, triangle, FiniteElement, TrialFunction, TestFunction)
```
Perhaps not so hard to patch in this instance.

**Comment by drew-parsons** [comment]
It's reasonable to require old dolfin .ufl files to explicitly import ufl components.  Functionality seems to be otherwise the same (old dolfin and ffc tests pass after such patching). I created a dolfin patch at https://bitbucket.org/fenics-project/dolfin/pull-requests/551 

That is a separate uflx module is not (yet) needed at this point in time, so I'll close this Issue, taking it to be sufficiently addressed by dolfin PR#551.
